### ISSUE TITLE
Email address required for purchases?!

### ISSUE THREAD

**Issue by yojimble** [PlebeianApp/plebeian.market#395]
![Opera Snapshot_2024-11-14_211447_staging plebeian market](https://github.com/user-attachments/assets/ca9f2b38-b3c6-433b-a456-95bfae00fb43)

boooo

**Comment by plebomoto** [comment]
We will remove this ASAP.

**Comment by yojimble** [comment]
🔥🔥

**Comment by yojimble** [comment]
for local pick up no email address is required, for delivery the box is not marked as required but does not allow continue without entering info
![Opera Snapshot_2024-12-09_123314_staging plebeian market](https://github.com/user-attachments/assets/86b5ed79-876c-4823-b87f-dae3db5e3c61)

**Comment by gzuuus** [comment]
Ups, working on it

**Comment by gzuuus** [comment]
should b fixed

**Comment by yojimble** [comment]
not yet, how do I do hard reset? just refresh and log in?

**Comment by gzuuus** [comment]
to hard refresh you need to clean the cache, depending on your browser this is done in different ways. But definitely i will recommend you to update your old Opera browser 👌

**Comment by yojimble** [comment]
hehe sadly is already the highest version available on windows 7, and I would go back to XP if I could!

email bug looks fixed now
