### ISSUE TITLE
Orders & sales dissapeared from dashboard

### ISSUE THREAD

**Issue by yojimble** [PlebeianApp/plebeian.market#401]
![Opera Snapshot_2024-11-17_172851_staging plebeian market](https://github.com/user-attachments/assets/d3fe874b-7f62-4b13-9f35-de6d0cb1f425)
![Opera Snapshot_2024-11-17_172954_staging plebeian market](https://github.com/user-attachments/assets/a6264720-7b7d-44bd-bf23-7fa1200f092a)
![Opera Snapshot_2024-11-17_172933_staging plebeian market](https://github.com/user-attachments/assets/ee227596-dc56-4338-ad6d-8a99009e3877)

**Comment by gzuuus** [comment]
This is because we reset the db every time we deploy new changes. We can add a function to import these jobs if they are not in the db

**Comment by yojimble** [comment]
understood
