### ISSUE TITLE
New Product Shipping Cost and Currency Selection

### ISSUE THREAD

**Issue by bitcoinbekka** [PlebeianApp/plebeian.market#424]
I see that there is a the option to add shipping to each product when you create a new product, it would make sense when you are making a New Stall that there is a note that the shipping methods entered under the Stall will be displayed as your shipping options when you add a "Product" 

I see that the currency is in SATS, there should be a note somewhere saying that if you select your currency in the Stall that is what the currency will be across the board, for the product and for shipping for each product created within the stall.

I think I made a mistake in selecting SATS as my default currency... it would be more helpful if the currency was dollars and SATS was displayed underneath the dollar amount, since final payment will be completed in SATS anyways

![testing notes 9](https://github.com/user-attachments/assets/f6bed17b-56aa-4d36-926e-ea415f720627)

**Comment by gzuuus** [comment]
Yes, we need some UX help to really tackle these issues. Good thing, you can always go to your stall and change the currency, this will give you the currency to set the prices in the shipping and so on.
