### ISSUE TITLE
No Checkout in Cart in the Chrome browser 

### ISSUE THREAD

**Issue by bitcoinbekka** [PlebeianApp/plebeian.market#425]
When I add products to the cart in Chrome the cart displays the items but says the cart is empty but when I add products to the cart in the Brave browser it displays the products and the checkout button 
![testing notes 11 - Brave browser](https://github.com/user-attachments/assets/ebb2e152-ce0e-48b6-9a82-2c3d58777b18)
![testing notes 10-Chrome window](https://github.com/user-attachments/assets/9f9c04a8-03af-4b96-8d0b-d301e24a20ab)

**Comment by yojimble** [comment]
this is possibly not chrome but because with each update my payment details disappear ...

**Comment by gzuuus** [comment]
Yes, this is not related with the browser

**Comment by yojimble** [comment]
it only seems to appear with a seller who hasn't entered payment details, and now only for a split second (maybe slow computer/internet).

Can test with this product on front page: https://staging.plebeian.market/products/_@sovereignengineering.io/sec-tshirt-light-eny0qgzntb


![2024-12-09 12_29_13-Greenshot](https://github.com/user-attachments/assets/b9c772a6-01ee-4e47-99d5-61aab383dd4c)
![2024-12-09 12_29_04-Greenshot](https://github.com/user-attachments/assets/c79bf26d-7ccb-4b76-8e39-712f01288cf0)
