### ISSUE TITLE
category totals superscripted

### ISSUE THREAD

**Issue by yojimble** [PlebeianApp/plebeian.market#456]
the numbers dont quite line up

![Opera Snapshot_2024-11-30_193422_staging plebeian market](https://github.com/user-attachments/assets/007a1c1f-bd5a-4b4f-9b89-a044a6318daa)

**Comment by plebomoto** [comment]
Cant reproduce:

<img width="300" alt="image" src="https://github.com/user-attachments/assets/ba05bf8c-6fc4-46c7-a8ef-ecfa9e9706b4">

**Comment by yojimble** [comment]
yep, looks good now

![Opera Snapshot_2024-12-09_121408_staging plebeian market](https://github.com/user-attachments/assets/c446ff6e-c4da-435f-9618-b7cf804f205a)
