### ISSUE TITLE
error after payment

### ISSUE THREAD

**Issue by yojimble** [PlebeianApp/plebeian.market#458]
![Screenshot_20241201_210237-1](https://github.com/user-attachments/assets/1d69e20b-37e3-4524-97cd-17929dd6a32f)

After completing checkout and with invoice paid this error appeared, the item is still visible in the cart and has not registered under the purchases tab

![WhatsApp Image 2024-12-01 at 21 11 44](https://github.com/user-attachments/assets/bc6469c6-012e-48ed-9a92-f52ef31b1e9c)

![Opera Snapshot_2024-12-01_211003_staging plebeian market](https://github.com/user-attachments/assets/7619c168-896f-4e8e-9096-ccedc0b19856)

**Comment by yojimble** [comment]
![Opera Snapshot_2024-12-01_211806_staging plebeian market](https://github.com/user-attachments/assets/b44c195d-5330-4962-9c5d-27d331f1f5a5)

order successfully registers in nostr dms

**Comment by gzuuus** [comment]
Can you provide more details? I cannot reproduce it

**Comment by yojimble** [comment]
it is order: #order-rene02kl4g created at 12/1/2024, 9:00:28 PM with stall Jimbles Jumble

'clicking go to dashboard' from the dms gives a 404 error
