### ISSUE TITLE
[design/bug?] no payment requested

### ISSUE THREAD

**Issue by yojimble** [PlebeianApp/plebeian.market#459]
there are some items which do not generate invoices, only 'place order'

![Opera Snapshot_2024-12-01_211506_staging plebeian market](https://github.com/user-attachments/assets/81059e51-72e3-4e72-a683-f29d0a23918c)

in dashboard the only option is cancel
![Opera Snapshot_2024-12-01_212851_staging plebeian market](https://github.com/user-attachments/assets/7702eea0-860f-4878-9e98-5c62486c40ed)

do we await contact from the seller?

**Comment by gzuuus** [comment]
Yes, if the merchant doesn't have payment details the only option is just 'place order', after that you just can wait for the merchant to contact you
