### ISSUE TITLE
UX: Save Progress in Add Product Modal (2 of 21)

### ISSUE THREAD

**Issue by Zazawowow** [PlebeianApp/plebeian.market#497]
### **User Story:**

As a seller adding a product to Plebeian Market, I want my input data to be automatically saved when I exit the add product modal, so that I don't lose my progress and can easily continue from where I left off when I return.

### **Acceptance Criteria:**

1. When a user exits the add product modal, any data entered should be saved automatically.
2. Upon reopening the add product modal, previously entered data should be restored, allowing the user to continue from where they left off.
3. If a user manually clears or submits the data, the stored progress should be reset.

Value Score: 12
Priority: 2 / 21 (as of 16th December 2024)

No design needed, could have a notification 'Your product details have been saved" using the same modal as the current one that reloads the page when a new version has come out.

**Comment by gzuuus** [comment]
@Zazawowow do you think the notification is necessary? How will this work within page refreshes? Should the data be persisted between reloads or just during the session? If it's just during the session as seems more logical the notification/toast may not be the best approach as it kind of reinforces the idea the data will be persisted between reloads, and makes more sense to just make it invisible to the user.

**Comment by Zazawowow** [comment]
Ok, that's fine, it was just an extra bit of feedback for the user but not probably not necessary. 

It's fine not to persist between refreshes if that's an issue, I don't see that being a usual circumstance and I don't thnk I'd expect that as normal behaviour.

Thanks.
