### ISSUE TITLE
UX: Enhance Shipping from layout and field (7 of 21)

### ISSUE THREAD

**Issue by Zazawowow** [PlebeianApp/plebeian.market#501]
### **User Story:**

As a seller adding a product and entering shipping information, I want an inline search field instead of a button-activated field, so that I can input and view my shipping address directly and quickly, with real-time updates, and the ability to anonymize the exact address information if needed.

### **Acceptance Criteria**

1. Replace the current button-triggered search field for shipping with an inline search field.
2. When a user begins typing, a list of address suggestions should dynamically appear.
3. The shipping preview should be displayed above the search field to be less prone to interaction errors
4. The field should display the actual address selected by the user until the address marker is moved, at which point the address should be anonymized for privacy.

Value Score: 10
Priority: 7 / 21 (as of 16th December 2024)

[Universal Design](https://www.figma.com/design/re69Ae2WVk5yKdaGxCbnb5/Plebeian-Design?node-id=1032-8646&t=yOd8gT0UnoCqwMjF-1)

**Comment by gzuuus** [comment]
Just tackling this issue, already solved, wdyt?
![Screenshot_20241217_131511](https://github.com/user-attachments/assets/143f1a0e-ed97-4bdf-80c7-20ee93650279)
![Screenshot_20241217_131646](https://github.com/user-attachments/assets/dfa0bc9a-4e19-4312-8086-c1a4786d23e7)

**Comment by gzuuus** [comment]
Also disabled the scroll on the map

**Comment by Zazawowow** [comment]
Great, just looking forward to the layout of the dropdown being updated to full width of the field. I believe that's part of a update buttons and forms task. TY Gzuuus.
